### ISSUE TITLE
Add `run` mode

### ISSUE THREAD

**Issue by killercup** [killercup/waltz#9]
The idea is waltz through a guide, and act like a human reader would: Copypasta some code into files, and run shell commands.

## Syntax

Annotate a code block like this

    ```sh,run=bash
    cd  foo
    cargo run --example foo-bar
    ```

## `waltz run`

1. For each code block
  1. Write code block to file/append content to file
  2. If the mode is `run`, execute the file with the set command

## Implementation steps, and feature ideas

- [ ] Parse `run=<cmd>`
- [ ] Allow omitting file name when `run` is set (generate random file name with extenstion based on code block lang)
- [ ] Default `<cmd>` based on code block language (sh = `sh foo.sh`, bash = `bash foo.sh`, rust = `rustc -o foo foo.rs && ./foo`, etc.)
- [ ] Cleverly assert command's exit code, e.g. by setting `set -e` in shell scripts

**Comment by norcalli** [comment]
On linux/unix systems you can use `file=/dev/stdout` and pipe it to another process to run too (since you can't use `run=sh` without a `file` as an anonymous script). Or if you're interested in something more peculiar you can combine that with `#!/usr/bin/env -S bash -c 'waltz $0 | bash'` on the first line, and make your markdown files executable.
